### PR TITLE
Update plugin

### PR DESCRIPTION
**Pull request by baev**
The first step to update Allure Jenkins plugin. I'll add more commits  during the work
- [x] add more tests (an example, tests for matrix jobs)
- [x] fix sonar issues
- [x] fix findbugs issues
- [x] add history support
- [x] add executor support
- [x] change artifact coordinates
- [x] bump Jenkins version to 2.7
- [x] migrate to java 8
- [x] support pipeline
- [x] add pipeline tests
- [x] make sure that all Windows issues are fixed
- [x] add more tests for different Jenkins locations and results paths (Windows escape issue)
- [ ] ~~manage build status~~
- [ ] ~~resolve environment vars in configuration~~
- [ ] ~~use allure command line from PATH if tool not installed~~
- [ ] ~~allure config support (removed during refactoring)~~

## Overview

screen shot 2016-10-26 at 02 15 28
## Overview for aggregated test run

screen shot 2016-10-26 at 02 28 13
## Test case

screen shot 2016-10-26 at 02 29 29

### CODE REVIEW

**Comment by baev** [comment]
@pupssman @mavlyutov @eroshenkoam feel free to start review of changes

**Comment by pupssman** [comment]
Looks shiny!

**Comment by beniamin-kis** [comment]
Any news on finishing this soon and releasing a new plugin version?

**Comment by monolithed** [comment]
@baev, Reporter does not work. Can you fix critical issues separately?

**Comment by jaceksokol** [comment]
PipelineIT test fix:
1. This step requires additional context, you need to put it into `node { ... }`
2. Use direct script definition instead of script file (there is some issue with correct namespace injection into this build step)
3. Update some dependencies (for tests).
4. `sample-jenkinsFile` can be deleted as it's no longer required

```
        <dependency>
            <groupId>org.jenkins-ci.plugins</groupId>
            <artifactId>script-security</artifactId>
            <version>1.24</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jenkins-ci.plugins.workflow</groupId>
            <artifactId>workflow-durable-task-step</artifactId>
            <version>2.4</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.jenkins-ci.plugins.workflow</groupId>
            <artifactId>workflow-basic-steps</artifactId>
            <version>2.1</version>
            <scope>test</scope>
        </dependency>
```

PipelineIT.java:
```
package io.qameta.jenkins;

import hudson.FilePath;
import hudson.model.ParametersDefinitionProperty;
import hudson.model.StringParameterDefinition;
import org.jenkinsci.plugins.workflow.cps.CpsFlowDefinition;
import org.jenkinsci.plugins.workflow.flow.FlowDefinition;
import org.jenkinsci.plugins.workflow.job.WorkflowJob;
import org.jenkinsci.plugins.workflow.job.WorkflowRun;
import org.junit.BeforeClass;
import org.junit.ClassRule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
import org.jvnet.hudson.test.BuildWatcher;
import org.jvnet.hudson.test.JenkinsRule;

import java.io.IOException;
import java.io.InputStream;

import static io.qameta.jenkins.testdata.TestUtils.*;

/**
 * @author charlie (Dmitry Baev).
 */
public class PipelineIT {

    @ClassRule
    public static BuildWatcher buildWatcher = new BuildWatcher();

    @ClassRule
    public static JenkinsRule jRule = new JenkinsRule();

    @ClassRule
    public static TemporaryFolder folder = new TemporaryFolder();

    public static String commandline;

    public static String jdk;

    @BeforeClass
    public static void setUp() throws Exception {
        jdk = getJdk(jRule);
        commandline = getAllureCommandline(jRule, folder);
    }

    @Test
    public void shouldSupportPipeline() throws Exception {
        WorkflowJob project = jRule.createProject(WorkflowJob.class);
        prepareWorkspace(project);

        FlowDefinition definition = new CpsFlowDefinition("node { allure(resultsPaths: [paths]) }", true);
        project.setDefinition(definition);
        project.addProperty(new ParametersDefinitionProperty(
                new StringParameterDefinition("paths", "allure-results")
        ));
        WorkflowRun build = jRule.buildAndAssertSuccess(project);
        assertHasReport(build);
    }

    private void prepareWorkspace(WorkflowJob project) throws IOException, InterruptedException {
        FilePath workspace = jRule.jenkins.getWorkspaceFor(project);
        String testSuiteFileName = "sample-testsuite.xml";
        FilePath allureReportsDir = workspace.child("allure-results").child(testSuiteFileName);
        InputStream testResultStream = getClass().getClassLoader().getResourceAsStream(testSuiteFileName);
        allureReportsDir.copyFrom(testResultStream);
    }
}
```

**Comment by jaceksokol** [comment]
Maybe I may be missing something but AFAIK Jenkins will not let you use plugin compiled to class file version 52. And it's also the reason for currently failing tests (but you must have already noticed that).

**Comment by baev** [comment]
@jaceksokol thank you so much

**Comment by etki** [comment]
just wanted to say this looks fantastic, anticipating

**Comment by baev** [comment]
Everything is done for now, we are working on release (it is gonna be other plugin since artifactId was changed). Will release BETA1 ASAP.

BTW you guys you can try it out. It works like a charm with a new beta of the report https://github.com/allurefw/allure-report/releases/tag/2.0-BETA1

Any feedback is really appreciated

**Comment by lanwen** [comment]
great work! 👍

**Comment by pupssman** [comment]
@baev changelist looks impressive!
But tell me -- why do you change `artifactId`, effectively retiring old plugin and introducing a new one instead? 
That makes it harder to upgrade -- so what's the PRO part of this change?
Will new and old plugins coexist on same J?

**Comment by baev** [comment]
@pupssman yeah, the idea is that you can use them both on the same Jenkins. And as far as I know Jenkins plugin dev guide says to not use `plugin` and `jenkins` words in name of the plugin, so that is good time to change plugin name as well (anyway other changes break backward compatibility)

**Comment by pupssman** [comment]
IMO changing the "owning entity" and stuff in a plugin is not right thing to do anyway. Removing `plugins` is good, changing `ru.yandex -> io.qameta` is at least questionable. 
Also, why breaking compatibility?

**Comment by eroshenkoam** [comment]
https://github.com/jenkinsci/allure-plugin/pull/70

**Pull request closed without merging**
