### PR TITLE
#49: Pipeline support

### PR DESCRIPTION
**Pull request by jaceksokol**
This is my PR as a result to lack of Pipeline support.

### CODE REVIEW

**Comment by baev** [comment]
@jaceksokol hi!

Thanks for all the work. Did you see https://github.com/jenkinsci/allure-plugin/pull/62 ?

**Comment by jaceksokol** [comment]
Yep, I've seen that one. However I required support for pipeline sooner than that work will be completed to I've decided to create my own implementation. And as I remember Pipeline support isn't available yet in that PR, is it?

**Comment by baev** [comment]
> However I required support for pipeline sooner than that work will be completed

Almost all the work is done. We will release a new version in few days

> And as I remember Pipeline support isn't available yet in that PR, is it?

Nope, it works:

```groovy
allure([resultsPaths: ['target/allure-results']])
```

**Comment by jaceksokol** [comment]
Thanks for into. I'm closing my PR.

**Comment by baev** [comment]
btw it would be nice if you review and test #62 

I have some problems with tests for pipeline (just spent few hours trying to fix it). And I feel like merge it right now and continue the work in separate PR.

**Pull request closed without merging**
